<?php
namespace Straker\EasyTranslationPlatform\Model\ResourceModel\AttributeTranslation;

use Straker\EasyTranslationPlatform\Model;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected function _construct()
    {
        $this->_init('Straker\EasyTranslationPlatform\Model\AttributeTranslation',
            'Straker\EasyTranslationPlatform\Model\ResourceModel\AttributeTranslation');
    }

//    function _renderFiltersBefore()
//    {
//        $this->_setIdFieldName( 'website_group_store' );
//        $this->getSelect()->joinLeft(
//            ['o' => $this->getTable('straker_attribute_option_translation')],
//            'main_table.attribute_translation_id = o.attribute_translation_id',
//            ['option_original_value' => 'o.original_value', 'o.option_translated_value' => 'o.translated_value']
//        );
//
//        return parent::_renderFiltersBefore(); // TODO: Change the autogenerated stub
//    }
}
