<div>
    <p>Please select the destination Store View where you would like this translation to show.</p>
</div>
<div class="admin__field field required _required">
    <label for="source" class="label admin__field-label">
        <span><?php echo __('Destination Store View:') ?></span>
    </label>
    <div class="admin__field-control control">
        <select name="source" class="required-entry _required select admin__control-select">
            <option value=""><?php echo __('Pick a store view') ?></option>
            <?php foreach ($block->getWebsites() as $website): ?>
                <?php $showWebsite = false; ?>
                <?php foreach ($website->getGroups() as $group): ?>
                    <?php $showGroup = false; ?>
                    <?php foreach ($group->getStores() as $store): ?>
                        <?php if ($showWebsite == false): ?>
                            <?php $showWebsite = true; ?>
                            <optgroup label="<?php echo $this->escapeHtml($website->getName()) ?>"></optgroup>
                        <?php endif; ?>
                        <?php if ($showGroup == false): ?>
                            <?php $showGroup = true; ?>
                            <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($group->getName()) ?>">
                        <?php endif; ?>
                        <option
                            value="<?php echo $this->escapeHtml($store->getId()) ?>"<?php if ($this->getStoreId() == $store->getId()): ?> selected="selected"<?php endif; ?>>
                            &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($store->getName()) ?></option>
                    <?php endforeach; ?>
                    <?php if ($showGroup): ?>
                        </optgroup>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </select>
    </div>
</div>