<?php
/**
 * @see StrakerTranslations_EasyTranslationPlatform_Block_Adminhtml_New_Products
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:80%;"><h3 class="icon-head head-products"><?php echo Mage::helper('strakertranslations_easytranslationplatform')->__('Select Attributes to Translate') ?></h3><h3 class="store-info-heading"><?php echo Mage::helper('strakertranslations_easytranslationplatform')->renderNewJobHeading($this->getRequest()->getParam('store')) ?></h3></td>
            <td class="a-right">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<ol class="wizard" data-wizard-steps="4">
    <li class="wizard-done"><?php echo $this->__('Select Job Type') ?></li>
    <li class="wizard-done"><?php echo $this->__('Select Details') ?></li>
    <li class="wizard-todo"><?php echo $this->__('Select Content') ?></li>
    <li class="wizard-todo"><?php echo $this->__('Confirm Content') ?></li>
</ol>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
<script>
    Event.observe(window, "load", function() {
        var buttonHtml = '<button title="Submit" type="button" class="right" onclick="attributeGrid_massactionJsObject.apply()" style=""><span><span><span>Submit</span></span></span></button>';
        $('attributeGrid').insert({after: buttonHtml});
        $$('.content-header-floating .content-header td.a-right')[0].insert(buttonHtml);
    });
</script>