<div class="content-header">
    <h3><?php echo Mage::helper('strakertranslations_easytranslationplatform')->__('Create New Job') ?></h3>
</div>
<div class="straker-main-container">
    <h1><?php echo Mage::helper('strakertranslations_easytranslationplatform')->__('Select your Destination Store View') ?></h1>
    <p><?php echo Mage::helper('strakertranslations_easytranslationplatform')->__('Please select the destination Store View where you would like this translation to show.') ?></p>
    <form id="selectstore-form" action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/straker_new/selectstore") ?>" >
        <div class="destination-container input-box input-left"><label for="store"><?php echo Mage::helper('strakertranslations_easytranslationplatform')->__('Destination Store View') ?></label>
            <select class="validate-select" name="store">
                    <option value=""><?php echo Mage::helper('strakertranslations_easytranslationplatform')->__('Pick a store view') ?></option>
                <?php foreach (Mage::app()->getWebsites() as $website): ?>
                    <?php $showWebsite = false; ?>
                    <?php foreach ($website->getGroups() as $group): ?>
                        <?php $showGroup = false; ?>
                        <?php foreach ($group->getStores() as $store): ?>
                            <?php if ($showWebsite == false): ?>
                                <?php $showWebsite = true; ?>
                                <optgroup label="<?php echo $this->escapeHtml($website->getName()) ?>"></optgroup>
                            <?php endif; ?>
                            <?php if ($showGroup == false): ?>
                                <?php $showGroup = true; ?>
                                <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($group->getName()) ?>">
                            <?php endif; ?>
                            <option value="<?php echo $this->escapeHtml($store->getId()) ?>">&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($store->getName()) ?></option>
                        <?php endforeach; ?>
                        <?php if ($showGroup): ?>
                            </optgroup>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </select>
            <div class="form-buttons">
                <input type="submit" onchange="selectstoreForm.submit()" class="form-button" value="<?php echo Mage::helper('strakertranslations_easytranslationplatform')->__('Next'); ?>" title="<?php echo Mage::helper('strakertranslations_easytranslationplatform')->__('Next'); ?>">
            </div>
        </div>
    </form>
</div>
<script>
    var selectstoreForm = new varienForm('selectstore-form');
</script>