<div class="content-header">
    <h3><?php echo $this->__('Job Type') ?></h3><h3 class="store-info-heading"><?php echo Mage::helper('strakertranslations_easytranslationplatform')->renderNewJobHeading($this->getRequest()->getParam('store')) ?></h3>
</div>
<ol class="wizard" data-wizard-steps="4">
    <li class="wizard-todo"><?php echo $this->__('Select Job Type') ?></li>
    <li class="wizard-todo"><?php echo $this->__('Select Details') ?></li>
    <li class="wizard-todo"><?php echo $this->__('Select Content') ?></li>
    <li class="wizard-todo"><?php echo $this->__('Confirm Content') ?></li>
</ol>
<div class="straker-main-container border">
    <h1><?php echo $this->__('Select Job Type') ?></h1>
    <p><?php echo $this->__('Select the content type you would like to send for translation.') ?></p>
    <div class="job-type-btn-wrap" style="padding:0; margin-bottom: 30px;">
        <?php echo $this->renderTypes(); ?>
    </div>
</div>
