<?php
/** @var $block \Straker\EasyTranslationPlatform\Block\Adminhtml\Job\Index */
?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Ui/js/modal/alert',
        'Magento_Ui/js/modal/confirm'
    ], function ($, alert, confirm) {
        var myAccountButton = $('.straker-my-account-button');

        if( typeof myAccountButton.get(0) !== 'undefined' ){
            var url = '<?php echo $block->_getMyAccountUrl(); ?>';_
            myAccountButton.on('click', function (e) {
                e.preventDefault();
                window.open(url, '_blank');
            });
        }
//        $(function () {
//            var anchorContent = $('#anchor-content');
//            var jobGrid = $('#straker-job-grid');
//            var quoteDiv = $('#straker-quote-frame');
//            var loadingMask = $('.admin__data-grid-loading-mask');
//
//            var refreshAllButton = $('#refresh-all-job');
//            var formKey = $('input[name="form_key"]').val();
//
//            if( typeof refreshAllButton.get(0) !== 'undefined' ){
//                refreshAllButton.prop('onclick', null);
//                refreshAllButton.on('click',function ( e ) {
//                    e.preventDefault();
//                    loadingMask.show();
//                    $.ajax({
//                        url: '<?php //echo $this->getUrl('EasyTranslationPlatform/Jobs/RefreshJob'); ?>//',
//                        dataType: 'json',
//                        data: { }
//                    }).done(function (data, textStatus ) {
//                        loadingMask.hide();
//                        console.log(data);
//                        if ( textStatus == 'success' && data.status) {
//                            confirm({
//                                title: '<?php //echo __("Please Confirm") ?>//',
//                                content: '<?php //echo __('Do you want update the job(s)?') ?>//',
//                                actions: {
//                                    confirm: function () {
//                                        location.reload();
//                                    }
//                                }
//                            });
//                        } else {
//                            alert({
//                                title: '',
//                                content: data.message
//                            });
//                        }
//                    });
//                })
//            }
//
//            if (typeof jobGrid.get(0) !== 'undefined') {
//                anchorContent.on('click', 'a', function (e) {
//                    //e.preventDefault();
//
//                    var jobKey = $(this).data('jobKey');
//                    var jobId = $(this).data('jobId');
//
//                    // if( jobId ){
//                    if ($(this).hasClass('straker-job-view-anchor')) {
////                        console.log('view job for ' + jobKey);
//                        $.ajax({
//                            url: '<?php //echo $this->getUrl('EasyTranslationPlatform/Jobs/ViewJob'); ?>//',
//                            data: {job_key: jobKey},
//                            dataType: 'json',
//                            success: function (response) {
//                                if (response.Success) {
//                                    quoteFrame.prop('src', response.JobKey);
//                                    quoteFrame.load();
//                                    quoteFrame.load();
//                                    jobGrid.hide();
//                                    quoteDiv.show();
////                                    console.log(response);
//                                }
//                            }
//
//                        });
//                    }
//
//                    if ($(this).text() == 'View Quote') {
//                        var viewJobId = $(this).closest('tr').children('.job-id').find('.data-grid-cell-content').text();
//                        loadingMask.show();
//                        var quoteFrame = quoteDiv.find('iframe');
////                        console.log($(this).closest('tr').children('.job-id').find('.data-grid-cell-content').text());
//                        $.ajax({
//                            url: '<?php //echo $this->getUrl('EasyTranslationPlatform/Jobs/ViewQuote'); ?>//',
//                            data: { job_id: viewJobId },
//                            dataType: 'json',
//                            success: function (response) {
//                                if (response.Success) {
//                                    quoteFrame.prop('src', response.JobKey);
//                                    quoteFrame.load(function () {
//                                        jobGrid.hide();
//                                        loadingMask.hide();
//                                        quoteDiv.show();
//                                    });
//
////                                    console.log(response);
//                                }
//                            }
//
//                        });
//                    }
//
//                    if ($(this).hasClass('straker-job-confirm-anchor')) {
////                        console.log('confirm job for ' + jobKey);
//                    }
//
//                    if ($(this).hasClass('straker-job-refresh-anchor')) {
//                        loadingMask.show();
//                        $.ajax({
//                            url: '<?php //echo $this->getUrl('EasyTranslationPlatform/Jobs/RefreshJob'); ?>//',
//                            data: {job_key: jobKey, job_id: jobId},
//                            dataType: 'json'
//                        }).done(function (data, textStatus ) {
//                            loadingMask.hide();
//                            if ( textStatus == 'success' && data.status) {
////                                console.log(data);
//                                confirm({
//                                    title: '<?php //echo __("Please Confirm") ?>//',
//                                    content: '<?php //echo __('The job have a new status, please refresh the page by pressing [OK]') ?>//',
//                                    actions: {
//                                        confirm: function () {
//                                            location.reload();
//                                        }
//                                    }
//                                });
//                            } else {
//                                alert({
//                                    title: '',
//                                    content: data.message
//                                });
//                            }
//                        });
//                    }
//
//                    if ($(this).is('#back-to-grid')) {
////                        quoteDiv.hide();
////                        jobGrid.show();
//                        location.reload();
//                    }
//                     }
//
//                });
//            }
//        });
    });

</script>