<script>
    require([
        'jquery'
    ], function ($) {
        $(function () {
            var anchorContent = $('#anchor-content');
            var jobGrid = $('#straker-job-grid');
            var quoteDiv = $('#straker-quote-frame');

            if (typeof jobGrid.get(0) !== 'undefined') {
                anchorContent.on('click', 'a', function (e) {
                    //e.preventDefault();

                    var jobKey = $(this).data('jobKey');
                    var jobId = $(this).data('jobId');

                    // if( jobId ){
                    if ($(this).hasClass('straker-job-view-anchor')) {
                        console.log('view job for ' + jobKey);
                        $.ajax({
                            url: '<?php echo $this->getUrl('EasyTranslationPlatform/Jobs/ViewJob'); ?>',
                            data: {job_key: jobKey},
                            dataType: 'json',
                            success: function (response) {
                                if (response.Success) {
                                    quoteFrame.prop('src', response.JobKey);
                                    quoteFrame.load();
                                    quoteFrame.load();
                                    jobGrid.hide();
                                    quoteDiv.show();
                                    console.log(response);
                                }
                            }

                        });
                    }

                    if ($(this).hasClass('straker-view-quote-anchor')) {
                        var quoteFrame = quoteDiv.find('iframe');

                        $.ajax({
                            url: '<?php echo $this->getUrl('EasyTranslationPlatform/Jobs/ViewQuote'); ?>',
                            data: {job_key: jobKey},
                            dataType: 'json',
                            success: function (response) {
                                if (response.Success) {
                                    quoteFrame.prop('src', response.JobKey);
                                    quoteFrame.load();
                                    quoteFrame.load();
                                    jobGrid.hide();
                                    quoteDiv.show();
                                    console.log(response);
                                }
                            }

                        });
                    }

                    if ($(this).hasClass('straker-job-confirm-anchor')) {
                        console.log('confirm job for ' + jobKey);
                    }

                    if ($(this).hasClass('straker-job-refresh-anchor')) {
                        //console.log('refresh job for ' + jobKey);
                        $.ajax({
                            url: '<?php echo $this->getUrl('EasyTranslationPlatform/Jobs/RefreshJob'); ?>',
                            data: {job_key: jobKey, job_id: jobId},
                            dataType: 'json',
                            context: $(this),
                            showLoader: true,
                            complete: function (response) {
//                                if (response.Success) {
//                                    console.log(response);
//                                }
                                location.reload();
                            }

                        });
                    }

                    if ($(this).is('#back-to-grid')) {
                        quoteDiv.hide();
                        jobGrid.show();
                    }
                    // }

                });
            }
        });
    });

</script>