<script>
    require([
        'jquery'

    ], function ($) {

        if(localStorage.getItem('target_store_id'))
        {
            $('select[name="destination_store"]').val(localStorage.getItem('target_store_id'));
        };

        $(document).ajaxSend(function( event, jqxhr, settings ) {

            var target_store_id = $('select[name="destination_store"]').val();

            window.ajax_url = settings.url;

            if(window.ajax_url.toLowerCase().search('easytranslationplatform/jobs/products')>-1)
            {
                settings.data = settings.data+'&target_store_id='+target_store_id;

            }

        });

        $('select[name="destination_store"]').on( "change", function () {

            $.ajax({
                url: '<?php echo $block->getUrl('EasyTranslationPlatform/Jobs/CheckLanguagePairs') ?>',
                data: {
                    form_key: window.FORM_KEY,
                    target_store_id: $(this).val()
                },
                type: 'POST'

            }).done(function(response) {

                if(response.redirect_url)
                {
                    window.location.replace(response.redirect_url)

                }else{

                    window.onbeforeunload = function() {

                        localStorage.setItem('target_store_id', response.target_store_id);
                    };

                    window.location.reload()
                }

            })
        });

    });

</script>