<?php
    echo $block->getHtml();
?>

<script>
    require([
        'jquery'
    ], function ( $ ) {
        $(function () {
            var viewJobGrid = $('#straker_job_attribute_grid');
            var grid = $('#straker_job_attribute_grid_table > tbody');
            var rows = grid.children();
            rows.has('a.straker-view-option-anchor').css('cursor','pointer');

//            var spinner = '<div data-role="spinner" data-component="st_jobs_listing.st_jobs_listing.jobs_grid_columns" class="admin__data-grid-loading-mask" style="display:none">\
//                             <div class="spinner">\
//                                <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>\
//                             </div>\
//                          </div>';
//            $(spinner).appendTo(viewJobGrid);
//
//            var loadingMask = $('.admin__data-grid-loading-mask');

            viewJobGrid.on('click', 'tr', function ( e ) {
                e.preventDefault();
                var currentRow = $(this);
                var labelAnchor = currentRow.find('a');

                if( typeof labelAnchor.get(0) === 'undefined' || !labelAnchor.hasClass('straker-view-option-anchor')){
                    return false;
                }else{
                    console.log( labelAnchor.text() );
                    var attrTranslationId = labelAnchor.data('attrId');
                    var attrOptions = $('.straker-job-attribute-option-' + attrTranslationId);

                    if( typeof attrOptions.get(0) === 'undefined' ){
                       // loadingMask.show();
                        $.ajax({
                            url: '<?php echo $this->getUrl('EasyTranslationPlatform/Jobs/AttributeOption'); ?>',
                            data: {attributeTranslationId: attrTranslationId},
                            dataType: 'json',
                            showLoader :  true,
                            method: 'get'
                        }).done(function (data, textStatus ) {
                            if( textStatus == 'success' && data.status ){
                                var html = '<tr class="job-option straker-job-attribute-option-'+ attrTranslationId +'">\
                                                <td colspan="2"></td>\
                                                <td class="attr-option-td" colspan="2">\
                                                    <table class="attr-option-table" width="100%">';
                                $.each(data.option_data, function (index, element ) {
                                    html += '<tr>\
                                                <td class="a-left col-text col-original_value">' + element['original_value'] + '</td>\
                                                <td class="col-text col-translated_value">' + element['translated_value'] + '</td>\
                                             </tr>';
                                });
                                html += '</table></td></tr>';
                                $(html).insertAfter(currentRow);
                                resetClass();
                            }
                            //loadingMask.hide();
                        });
                    }else{
                        attrOptions.toggle();viewJobGrid.load();
                        resetClass();
                    }
                }

            });

            function resetClass() {
                console.log(rows.length);
                var i = 0;
                $.each(rows, function (index, row) {
                    $(row).removeClass('even');
                    if($(row).css('display') !== 'none'){
                        if( i % 2 ) {
                            $(row).addClass('even');
                        }
                        i++;
//                        console.log(i);
                    }

                });
            }

//            viewJobGrid.on('click', 'a', function( e ){
//                e.preventDefault();
////                console.log('234234234234'+loadingMask.css('display'));
//
//                if($(this).hasClass('straker-view-option-anchor')){
//                    var attrTranslationId = $(this).data('attrId');
//                    var currentRow = $(this).parent().parent();
////                    console.log( currentRow );
////                    currentRow.css('border','2px solid red');
//                    var attrOptions = $('.straker-job-attribute-option-' + attrTranslationId);
//
//                    if( typeof attrOptions.get(0) === 'undefined' ){
//                        loadingMask.show();
//                        $.ajax({
//                            url: '<?php //echo $this->getUrl('EasyTranslationPlatform/Jobs/AttributeOption'); ?>//',
//                            data: {attributeTranslationId: attrTranslationId},
//                            dataType: 'json',
//                            method: 'get'
//                        }).done(function (data, textStatus ) {
//                            if( textStatus == 'success' && data.status ){
//                                var html = '<tr class="straker-job-attribute-option-'+ attrTranslationId +'">\
//                                            <td colspan="2"></td>\
//                                            <td class="attr-option-td" colspan="2">\
//                                                <table class="attr-option-table" width="100%">';
//                                $.each(data.option_data, function (index, element ) {
//                                    html += '<tr>\
//                                                <td class="a-left col-text col-original_value">' + element['original_value'] + '</td>\
//                                                <td class="col-text col-translated_value">' + element['translated_value'] + '</td>\
//                                            </tr>';
//                                })
//                                html += '</table></td></tr>';
//                                $(html).insertAfter(currentRow);
//                                resetClass();
//                            }
//                            loadingMask.hide();
//                        });
//                    }else{
//                        attrOptions.toggle();
//                        resetClass();
//                    }
//                }
//            });
        });
    });
</script>