<?php
/**  @var $block \Straker\EasyTranslationPlatform\Block\Adminhtml\Job\ViewJob */
echo $block->getHtml();

/** @var $typeBlock \Straker\EasyTranslationPlatform\Block\Adminhtml\Job\ViewJob\Type */
$typeBlock = $block->getChildBlock('view_job_type_grid');
?>

<?php if ( $typeBlock !== false ): ?>

<div id="import-translation-modal" style="display: none;">
    <form id="import-translation-form" class="admin__fileldset" action="<?php echo $typeBlock->getImportUrl(); ?>" method="post" enctype="multipart/form-data">
        <?php echo $block->getBlockHtml('formkey')?>
        <input type="hidden" name="job_id" value="<?php echo $typeBlock->getJobId();?>" />
        <input type="hidden" name="job_key" value="<?php echo $typeBlock->getJobKey();?>" />
        <input type="hidden" name="source_store_id" value="<?php echo $typeBlock->getSourceStoreId();?>" />
        <p><?php echo __('This will import translation by uploading translated file.') ?></p>
        <fieldset class="fieldset admin__fieldset fieldset-wide">
            <legend class="admin__legend legend">
                <span></span>
            </legend><br>

            <div class="messages">
            </div>

            <div class="admin__field required">
                <label for="import_file_uploader" class="admin__field-label">
                    <span><?php /* @escapeNotVerified */ echo __('Upload Translated File') ?></span>
                </label>
                <div class="admin__field-control import-file-control">
                    <input type="file" id="import_file_uploader" name="translated_file" class="input-file required-entry"/>
                    <div class="straker_store_error_msg"><span></span></div>
                </div>
            </div>

        </fieldset>
    </form>
</div>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'loadingPopup',
        'mage/translate'
    ], function ( $, modal ) {
        var importTranslationModal = $('#import-translation-modal');

        if( typeof importTranslationModal !== 'undefined'){
            var importButton = $('#import_translated_file');
            var fileUploader = $('#import_file_uploader');

            if(typeof importButton !== 'undefined' && fileUploader !== 'undefined'){
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: $.mage.__('Import Translation'),
                    buttons: [
                        {
                            text: $.mage.__('Cancel'),
                            class: 'action cancel',
                            click: function () {
                                this.closeModal();
                            }
                        },
                        {
                            text: $.mage.__('Import'),
                            class: 'action primary',
                            click: function () {
                                var importTranslationForm = $('#import-translation-form');

                                if ( typeof importTranslationForm !== 'undefined') {
                                    importTranslationForm.mage('form').mage('validation');
                                    var filename = fileUploader.val();
                                    if (filename) {
                                        $('body').loadingPopup({
                                            timeout: false
                                        });

                                        importTranslationForm.submit();
                                    } else {
                                        showMessage('File not found.');
                                    }
                                }
                            }
                        }
                    ]
                };

                var popup = modal(options, importTranslationModal);

                function resetFileUploader(){
                    fileUploader.val('');
                    resetMessage();
                }

                function resetMessage() {
                    $('.straker_store_error_msg span').text('');
                }

                function showMessage(message){
                    $('.straker_store_error_msg span').text(message);
                }

                importButton.on('click', function ( e ) {
                    e.preventDefault();
                    resetFileUploader();
                    $('#import-translation-modal').modal('openModal');
                });

                fileUploader.on('change', function () {
                    if ($(this).val()) {
                        resetMessage();
                    }
                })
            }
        }
    })

</script>

<?php endif; ?>

<script>
    require([
        'jquery',
        'mage/translate'
    ], function ( $ ) {
        $(function () {
            var viewJobGrid = $('#straker_job_attribute_grid');
            var grid = $('#straker_job_attribute_grid_table > tbody');
            var rows = grid.children();
            rows.has('a.straker-view-option-anchor').css('cursor','pointer');

            viewJobGrid.on('click', 'tr', function ( e ) {
                e.preventDefault();
                var currentRow = $(this);
                var labelAnchor = currentRow.find('a');

                if( typeof labelAnchor.get(0) === 'undefined' || !labelAnchor.hasClass('straker-view-option-anchor')){
                    return false;
                }else{
//                    console.log( labelAnchor.text() );
                    var attrTranslationId = labelAnchor.data('attrId');
                    var attrOptions = $('.straker-job-attribute-option-' + attrTranslationId);

                    if( typeof attrOptions.get(0) === 'undefined' ){
                       // loadingMask.show();
                        $.ajax({
                            url: '<?php echo $this->getUrl('EasyTranslationPlatform/Jobs/AttributeOption'); ?>',
                            data: {attributeTranslationId: attrTranslationId},
                            dataType: 'json',
                            showLoader :  true,
                            method: 'get'
                        }).done(function (data, textStatus ) {
                            if( textStatus == 'success' && data.status ){
                                var html = '<tr class="job-option straker-job-attribute-option-'+ attrTranslationId +'">\
                                                <td colspan="2"></td>\
                                                <td class="attr-option-td" colspan="2">\
                                                    <table class="attr-option-table" width="100%">';
                                $.each(data.option_data, function (index, element ) {
                                    html += '<tr>\
                                                <td class="a-left col-text col-original_value">' + element['original_value'] + '</td>\
                                                <td class="col-text col-translated_value">' + element['translated_value'] + '</td>\
                                             </tr>';
                                });
                                html += '</table></td></tr>';
                                $(html).insertAfter(currentRow);
                                resetClass();
                            }
                            //loadingMask.hide();
                        });
                    }else{
                        attrOptions.toggle();viewJobGrid.load();
                        resetClass();
                    }
                }

            });

            function resetClass() {
                console.log(rows.length);
                var i = 0;
                $.each(rows, function (index, row) {
                    $(row).removeClass('even');
                    if($(row).css('display') !== 'none'){
                        if( i % 2 ) {
                            $(row).addClass('even');
                        }
                        i++;
                    }

                });
            }
        });
    });
</script>