<?php
/** @var $block \Straker\EasyTranslationPlatform\Block\Adminhtml\Settings\Config\BackupButton */
echo $block->getButtonHtml();
echo '<p class="note"><span>'. __('This will backup database.') .'</span>';
?>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'Magento_Ui/js/modal/confirm',
        'mage/translate'
    ], function ( $, alert, confirm ) {
        var backupButton = $('#demonstration_data_straker_backup_button');
        if( typeof backupButton != 'undefined'){
            backupButton.on('click', function (e) {
                e.preventDefault();
                confirm({
                    content: $.mage.__('Are you going to backup Magento database?'),
                    actions: {
                        confirm:  function () {
                            $.ajax({
                                url         : '<?php echo $block->getAjaxRequestUrl(); ?>',
                                showLoader  : true,
                                type        : 'get'
                            }).always(function ( data ) {
                                if(data.success){
                                    alert({
                                        title   : '',
                                        content : $.mage.__('Backup finished successfully.')
                                    });
                                }else{
                                    var msg = (typeof data.message != 'undefined') ? data.message : 'unknown';
                                    alert({
                                        title   : '',
                                        content : $.mage.__('Backup failed. Please try again. <p><b>Reason: </b>' + msg + '</p>')
                                    });
                                }
                            });
                        }
                    }
                });
            });
        }
    });
</script>
