<table>
    <?php foreach ($block->getWebsites() as $website) {
        $groups = $website->getGroups();

        if (count($groups) > 0) {
            foreach ($website->getGroups() as $group) { ?>
                <tr>
                    <td colspan="2" class="site-group-name">
                        <span> <?php echo __($website->getName()) . ' - ' . __($group->getName()); ?> </span>
                    </td>
                </tr>
                <?php $stores = $group->getStores();
                if (count($stores) > 0) {
                    foreach ($stores as $store) {
                        if ($store->getId() != \Magento\Store\Model\Store::DEFAULT_STORE_ID) { ?>
                            <tr class="store-view-list">
                                <td class="store-view-name">
                                    <span><?php echo __($store->getName()) ?></span>
                                </td>
                                <td class="clear-language">
                                    <input type="hidden" name="store-id" value="<?php echo $store->getId(); ?>"/>
                                    <?php echo $block->getClearStoreButtonHtml($store) ?>
                                </td>
                            </tr>
                        <?php }
                    }
                } else { ?>
                    <tr class="store-view-list">
                        <td colspan="2">
                            <span><?php echo __("No store views for this website."); ?></span>
                        </td>
                    </tr>
                    <?php
                }
            }
        } else { ?>
            <tr>
                <td colspan="2">
                    <span class="site-group-name"> <?php echo $website->getName(); ?> </span>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <span> <?php echo __("No stores for this website."); ?> </span>
                </td>
            </tr>
        <?php }

    } ?>
</table>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'Magento_Ui/js/modal/confirm'
    ], function ($, alert, confirm) {

        var $resetButton = $('.action-default.scalable.straker-reset-store-button');

        //disable save config button
        var saveButton = $('.save');
        if (saveButton.get(0) !== 'undefined') {
            saveButton.prop('disabled', 'disabled');
        }

        $resetButton.on('click', function (e) {
            e.preventDefault();

            var iStoreId = $(this).siblings('input[name=store-id]').val();

            if ($.isNumeric(iStoreId) && iStoreId > 0) {

                confirm({
                    title: '<?php echo __("Please Confirm") ?>',
                    content: '<?php echo __('Do you want to reset settings for this store view?') ?>',
                    actions: {
                        confirm: function () {
                            $.ajax({
                                url: '<?php echo $block->getAjaxResetUrl(); ?>',
                                data: {'store': iStoreId},
                                method: 'get',
                                complete: function () {
                                    location.reload();
                                }
                            });
                        }
                    }
                });

            } else {
                alert({
                    content: '<?php echo __('Store code is not valid.'); ?>',
                });
            }

        });
    });
</script>