<script>
    require([
        'jquery'
    ], function( $ ){
        var $resetButton = $('#straker_general_reset_account_button');
        $resetButton.on('click', function(){

            var bResult = window.confirm("Do you want reset all settings?");

            if( bResult ){
                $.ajax({
                    url      : '<?php echo $block->getAjaxResetUrl(); ?>',
                    //data     : { form_key: window.FORM_KEY },
                    method   : 'get',
                    dataType : 'json',
                    complete : function(){
                        location.reload();
                    }
                });
            }
        });
    });
</script>

<?php echo $block->getButtonHtml();