<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm'
    ], function( $, confirm ){

        var $resetButton = $('#straker_general_restore_product_data_button');

        $resetButton.on('click', function(){

            confirm({
                title: '<?php echo __("Please Confirm") ?>',
                content: '<?php echo __('Do you want to restore product data?') ?>',
                actions: {
                    confirm: function(){
                        $.ajax({
                            url      : '<?php echo $block->getAjaxResetUrl(); ?>',
                            method   : 'get',
                            complete : function(){
                                location.reload();
                            }
                        });
                    }
                }
            });
        });
    });
</script>

<?php echo $block->getButtonHtml();