<?php
/** @var $block \Straker\EasyTranslationPlatform\Block\Adminhtml\Settings\Config\RestoreButton */
echo $block->getButtonHtml();
echo '<p class="note"><span>'. __('This will restore database from the last backup.') .'</span>';
?>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'Magento_Ui/js/modal/confirm',
        'mage/translate'
    ], function ( $, alert, confirm ) {
        var backupButton = $('#demonstration_data_straker_restore_button');

        if( typeof backupButton != 'undefined'){
            backupButton.on('click', function (e) {
                console.log('<?php echo $block->getAjaxRequestUrl(); ?>');
                console.log(FORM_KEY);
                e.preventDefault();
                confirm({
                    content: $.mage.__('Are you going to restore Magento database, this process usually takes 3-4 minutes to complete?'),
                    actions: {
                        confirm:  function () {
                            $.ajax({
                                url         : '<?php echo $block->getAjaxRequestUrl(); ?>',
                                showLoader  : true,
                                type        : 'get'
                            }).always(function ( data ) {
                                if(data.success){
                                    alert({
                                        title   : '',
                                        content : $.mage.__('Restore finished successfully. Please login again and flush Magento caches.'),
                                        actions: {
                                            always: function () {
                                                location.reload();
                                            }
                                        }
                                    });
                                }else{
                                    var msg = (typeof data.message != 'undefined') ? data.message : 'unknown';
                                    alert({
                                        title   : '',
                                        content : $.mage.__('Restore failed. Please try again. <p><b>Reason: </b>' + msg + '</p>')
//                                        actions: {
//                                            always: function () {
//                                                location.reload();
//                                            }
//                                        }
                                    });
                                }
                            });
                        }
                    }
                });
            });
        }
    });
</script>
