<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('strakertranslations_easytranslationplatform')->__('Manage Jobs') ?></h3></td>
            <td class="a-right">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
<div class="straker-quote-container" id="straker-quote-container" style="display: none">
    <a id="straker-quote-back-link">Go Back to Jobs Grid</a>
    <div id="straker-quote-iframe-container"></div>
</div>
<script>
    viewStrakerQuote = function(jobId, jobKey) {
        event.stopPropagation();
        var paymentPageUrl = "<?php echo Mage::getStoreConfig('straker/api_url/payment_page') ?>";
        var iframe = '<iframe src="'+paymentPageUrl+'&job_key='+jobKey+'" width="100%" height="600"></iframe>';
        console.log(iframe);
        $('straker-quote-iframe-container'). update(iframe);
        //$('button-update-'+jobId).click();
        $('strakerJobGrid').hide();
        $('straker-quote-container').show();
    }
    Event.observe($('straker-quote-back-link'), 'click', function(){
        $('straker-quote-container').hide();
        $('strakerJobGrid').show();
    });
</script>