<?php
namespace Straker\EasyTranslationPlatform\Block\Adminhtml\Job;

use Magento\Framework\View\Element\AbstractBlock;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Result\LayoutFactory;
use Magento\Framework\View\Result\PageFactory;
use Straker\EasyTranslationPlatform\Model;

class ViewJob extends Template
{
    const BLOCK_TEMPLATE = 'job/view-job-detail-grid.phtml';

    protected $_resultLayoutFactory;
    protected $_resultPageFactory;

    function __construct(
        Template\Context $context,
        LayoutFactory $resultLayoutFactory,
        PageFactory $resultPageFactory,
        array $data
    )
    {
        $this->_resultLayoutFactory = $resultLayoutFactory;
        $this->_resultPageFactory = $resultPageFactory;
        parent::__construct($context, $data);
    }
    
    function _prepareLayout()
    {
        if (!$this->getTemplate()) {
            $this->setTemplate(static::BLOCK_TEMPLATE);
        }

        $requestData = $this->getRequest()->getParams();
//        var_dump($requestData);
        if( array_key_exists('job_type_id', $requestData )){
            $jobType = $requestData['job_type_id'];

            switch ( $jobType ){
                case Model\JobType::JOB_TYPE_ATTRIBUTE:
//                    $this->addChild('view_job_attribute_grid','Straker\EasyTranslationPlatform\Block\Adminhtml\Job\ViewJob\Attribute');
                    $this->addChild(
                        'view_job_attribute_grid',
                        'Straker\EasyTranslationPlatform\Block\Adminhtml\Job\ViewJob\Attribute',
                        [
                            'id' => 'view-job-attribute-grid'
                        ]
                    );
                    break;
                case Model\JobType::JOB_TYPE_PRODUCT:
                    $this->addChild(
                        'view_job_product_block',
                        'Straker\EasyTranslationPlatform\Block\Adminhtml\Job\ViewJob\Product',
                        [
                            'id' => 'view-job-product-grid'
                        ]
                    );
                    break;
                case Model\JobType::JOB_TYPE_CATEGORY:
                    $this->addChild(
                        'view_job_category_grid',
                        'Straker\EasyTranslationPlatform\Block\Adminhtml\Job\ViewJob\Category',
                        [
                            'id' => 'view-job-category-grid'
                        ]
                    );
                    break;
            }
        }

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub

    }
}