<div>
    <h2><?php echo __('Source') ?></h2>
    <p><?php echo __('Where would you like us to take your content from?') ?></p>
</div>
<div class="admin__field field required _required">
    <label for="source" class="label admin__field-label">
        <span><?php echo __('Source Store View:') ?></span>
    </label>
    <div class="admin__field-control control">
        <select name="source" class="required-entry _required select admin__control-select">
            <option value=""><?php echo __('Pick a store view') ?></option>
            <?php foreach ($block->getWebsites() as $website): ?>
                <?php $showWebsite = false; ?>
                <?php foreach ($website->getGroups() as $group): ?>
                    <?php $showGroup = false; ?>
                    <?php foreach ($group->getStores() as $store): ?>
                        <?php if ($showWebsite == false): ?>
                            <?php $showWebsite = true; ?>
                            <optgroup label="<?php echo $this->escapeHtml($website->getName()) ?>"></optgroup>
                        <?php endif; ?>
                        <?php if ($showGroup == false): ?>
                            <?php $showGroup = true; ?>
                            <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($group->getName()) ?>">
                        <?php endif; ?>
                        <option
                            value="<?php echo $this->escapeHtml($store->getId()) ?>"<?php if ($this->getStoreId() == $store->getId()): ?> selected="selected"<?php endif; ?>>
                            &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($store->getName()) ?></option>
                    <?php endforeach; ?>
                    <?php if ($showGroup): ?>
                        </optgroup>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </select>
    </div>
</div>

<div class="admin__field field required _required">
    <label for="language" class="label admin__field-label">
        <span><?php echo __('Select A Language:') ?></span>
    </label>
    <div class="admin__field-control control">
        <select name="language" class="required-entry _required select admin__control-select">
            <option value=""><?php echo __('Select A Language') ?></option>
            <?php foreach ($block->_getOptions() as $languages): ?>
                <option value="<?php echo $languages->code ?>"><?php echo $languages->name ?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>

<div>
    <h2><?php echo __('Destination') ?></h2>
    <p><?php echo __('Where would you like us to put the translated content?') ?></p>
</div>


<div class="admin__field field required _required">
    <label for="destination" class="label admin__field-label">
        <span><?php echo __('Select Destination Store:') ?></span>
    </label>
    <div class="admin__field-control control">
        <select name="destination" class="required-entry _required select admin__control-select">
            <option value="">
                <!-- <?php //echo Mage::getModel('core/store')->load($this->getSetupStoreId())->getName() ?> -->
            </option>
        </select>
        <input name="store" type="hidden" value="<?php echo $this->getSetupStoreId() ?>"/>
    </div>
</div>

<div class="admin__field field required _required">
    <label for="target" class="label admin__field-label">
        <span><?php echo __('Target Language:') ?></span>
    </label>
    <div class="admin__field-control control">
        <select name="target" id="target-language" class="required-entry _required select admin__control-select">
            <option value="">Select A Language</option>
            <?php foreach ($block->_getOptions() as $languages): ?>
                <option value="<?php echo $languages->code ?>"><?php echo $languages->name ?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>