<?php
    echo $block->getButtonHtml();
?>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'Magento_Ui/js/modal/confirm'
    ], function( $, alert, confirm ){

        var saveButton = $('.save');
        var translateButton = $('#demonstration_complete_job_translate_job');

        if( saveButton.get(0) !== 'undefined' ){
            saveButton.prop('disabled','disabled');
        }

        translateButton.on('click', function ( e ) {
            var tjNumberInput = $('#demonstration_complete_job_tj_number');
            var tjNumber = tjNumberInput.val();
            $.ajax({
                url: '<?php echo $this->getUrl('EasyTranslationPlatform/Jobs/CompleteJob'); ?>',
                method: 'get',
                data: { job_id: tjNumber },
                dataType: 'json',
                showLoader: true
            }).done(function (data, textStatus ) {
//                console.log(textStatus);
                if( textStatus == 'success' && data.success ) {
                    alert({
                        title: '',
                        content: '<?php echo __('Job completed successfully.'); ?>'
                    });
                    tjNumberInput.val('');
                    location.href = "<?php echo $this->getUrl('EasyTranslationPlatform/Jobs/Index'); ?>";
                }else{
                    alert({
                        title: '',
                        content: '<?php echo __('Failed to complete the job.'); ?>'
                    });
                }
            });
        });

//        $resetButton.on('click', function( e ){
//            e.preventDefault();
//
//            var iStoreId = $(this).siblings('input[name=store-id]').val();
//
//            if( $.isNumeric( iStoreId ) && iStoreId > 0 ){
//
//                confirm({
//                    title: '<?php //echo __("Please Confirm") ?>//',
//                    content: '<?php //echo __('Do you want to reset settings for this store view?') ?>//',
//                    actions: {
//                        confirm: function(){
//                            $.ajax({
//                                url      : '<?php //echo $block->getAjaxResetUrl(); ?>//',
//                                data     : { 'store' : iStoreId },
//                                method   : 'get',
//                                complete : function(){
//                                    location.reload();
//                                }
//                            });
//                        }
//                    }
//                });
//
//            }else{
//                alert({
//                    content: '<?php //echo __('Store code is not valid.'); ?>//',
//                });
//            }
//
//        });
    });
</script>
